language: node_js

cache: yarn

jobs:
  include:
    - stage: test
      node_js: "8"
    - stage: test
      node_js: "10"
    - stage: release
      node_js: "10"
      script: skip # Skip running "yarn test" again
      deploy:
        provider: script
        skip_cleanup: true
        script: yarn publish